# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

moran <- function(y, NN) {
    .Call('PoissonAutomodelViz_moran', PACKAGE = 'PoissonAutomodelViz', y, NN)
}

sim_mrfC <- function(meanpar, bet0, bet1, ens, eew, R, iter, a, NN) {
    .Call('PoissonAutomodelViz_sim_mrfC', PACKAGE = 'PoissonAutomodelViz', meanpar, bet0, bet1, ens, eew, R, iter, a, NN)
}

sim_mrfClog <- function(bet0, bet1, ens, eew, R, iter, a, NN) {
    .Call('PoissonAutomodelViz_sim_mrfClog', PACKAGE = 'PoissonAutomodelViz', bet0, bet1, ens, eew, R, iter, a, NN)
}

